steps:
- task: NuGetCommand@2
  displayName: 'Restore packages for Typewriter tool'
  inputs:
    restoreSolution: '$(typewriterSolution)'

- task: VSBuild@1
  displayName: 'Build Typewriter'
  inputs:
    solution: '$(typewriterSolution)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# TODO support metadata path
- task: PowerShell@2
  displayName: 'Transform metadata, run Typewriter and update models'
  inputs:
    targetType: 'inline'
    script: |
      $outputPath = Join-Path $env:Build_SourcesDirectory "output"
      Write-Host "Path to typewriter.exe output $outputPath"

      $typewriterPath = (Join-Path (Join-Path $env:Build_SourcesDirectory\MSGraph-SDK-Code-Generator\src\Typewriter\bin\ $(buildConfiguration)) Typewriter.exe)
      Write-Host "Path to typewriter tool: $typewriterPath"

      $metadataDir = "metadata"
      mkdir $metadataDir
      $metadataFile = Join-Path $metadataDir "metadata.xml"
      Invoke-WebRequest -Uri $(metadataURL) -OutFile $metadataFile
      Write-Host "Downloaded $(metadataURL) to $metadataFile" -ForegroundColor Green

      $xslTranformScriptPath = "$env:Build_SourcesDirectory\msgraph-metadata\transforms\csdl\transform.ps1"
      $xslPath = "msgraph-metadata\transforms\csdl\preprocess_csdl.xsl"
      $cleanMetadataFile = Join-Path $metadataDir "clean_metadata.xml"

      # transform script uses relative path to working directory
      & $xslTranformScriptPath -xslPath $xslPath -inputPath $metadataFile -outputPath $cleanMetadataFile
      Write-Host "Transformed $metadataFile to $cleanMetadataFile" -ForegroundColor Green

      Write-Host "Running Typewriter..."
      & $typewriterPath -v Info -m $cleanMetadataFile -o $outputPath -g Files

      $repoModelsDir = "$env:Build_SourcesDirectory\msgraph-sdk-dotnet\src\Microsoft.Graph\Generated\"
      Write-Host "Path to repo model directory: $repoModelsDir"

      Remove-Item -Recurse $repoModelsDir | Write-Host
      Write-Host "Removed the existing generated files in the repo." -ForegroundColor Green

      $modelsDirectory = Join-Path $outputPath "\com\microsoft\graph\"
      Move-Item $modelsDirectory $repoModelsDir
      Write-Host "Moved the models from $modelsDirectory into the local repo." -ForegroundColor Green

- task: PublishBuildArtifacts@1
  displayName: 'Publish metadata files as artifact'
  inputs:
   PathtoPublish: '$(Build.SourcesDirectory)\metadata'
   ArtifactName: 'metadata'
   publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Build Microsoft.Graph.dll'
  inputs:
    command: 'build'
    projects: msgraph-sdk-dotnet/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'