# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# contains an end to end validation pipeline using C# compilation tests for staging V1 metadata

trigger: none
pr: none
name: 'Staging V1 Validation Pipeline'

resources:
  repositories:
    - repository: microsoft-graph-docs
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-docs
      ref: master
    - repository: apidoctor
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/apidoctor
      ref: master
    - repository: microsoft-graph-devx-api
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-devx-api
      ref: dev
    - repository: MSGraph-SDK-Code-Generator
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/MSGraph-SDK-Code-Generator
      ref: main
    - repository: msgraph-sdk-dotnet
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-sdk-dotnet
      ref: dev
    - repository: msgraph-metadata
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-metadata

parameters:
- name: metadataURL
  displayName: 'URL for metadata for which SDK generation will happen:'
  type: string
  default: 'https://graph.microsoft.com/stagingv1.0/$metadata'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: e2e-templates/variables.yml
    parameters:
      metadataURL: ${{ parameters.metadataURL }}
      metadataVersion: 'v1.0'

steps:
  - template: e2e-templates/steps.yml
    parameters:
      shouldRunKnownFailures: false
      shouldRunSnippetGeneration: false
